name: Build

on:
  pull_request:
  workflow_call:

jobs:
  build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        os:
          [
            ubuntu-22.04,
            ubuntu-24.04,
            macos-14,
            macos-15,
            windows-2022,
            windows-2025,
          ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2

      - uses: conan-io/setup-conan@434f093a557d1ee6972c4ed78693c3191653537b # 1.1.0

      - name: Build
        shell: bash
        run: |
          conan install . --build=missing --update --settings=compiler.cppstd=17

